version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: trading_bot_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trading_bot_db
      MYSQL_USER: trading_user
      MYSQL_PASSWORD: trading_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trading_bot_network
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: trading_bot_orchestrator
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=mysql+pymysql://trading_user:trading_password@db:3306/trading_bot_db
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DOCKER_NETWORK=trading_bot_network
      - BOT_IMAGE=trading-bot:latest
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./orchestrator:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trading_bot_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  trading_bot_network:
    driver: bridge
